services:
      
  eureka-server:
    image: eurekaserver:latest
    container_name: eureka-server
    build:
      context: ./eureka
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8761
    ports:
      - "8761:8761"
    networks:
      - lotto-network

  category-db:
    image: mysql:8.0
    container_name: category-db
    restart: always
    command: --port=3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotto_categories
      MYSQL_USER: user
      MYSQL_PASSWORD: categories
    ports:
      - "3307:3307"
    volumes:
      - ./dbinit/category:/docker-entrypoint-initdb.d
    networks:
      - lotto-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  transaction-db:
    image: mysql:8.0
    container_name: transaction-db
    restart: always
    command: --port=3308
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotto_transactions
      MYSQL_USER: user
      MYSQL_PASSWORD: transactions
    ports:
      - "3308:3308"
    volumes:
      - ./dbinit/transaction:/docker-entrypoint-initdb.d
    networks:
      - lotto-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  lotto-category:
    image: lotto_category:latest
    container_name: lotto-category
    build:
      context: ./lotto_category
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://category-db:3307/lotto_categories
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: categories
      SPRING_APPLICATION_NAME: lotto-category
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
      category-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - lotto-network

  lotto-transaction:
    image: lotto_transaction:latest
    container_name: lotto-transaction
    build:
      context: ./lotto_transaction
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://transaction-db:3308/lotto_transactions
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: transactions
      SPRING_APPLICATION_NAME: lotto-transaction
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
      transaction-db:
        condition: service_healthy
      lotto-category:
        condition: service_started
    ports:
      - "8082:8082"
    networks:
      - lotto-network

  frontend:
    image: lotto-frontend:latest
    container_name: lotto-frontend
    build:
      context: ./lotto-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - lotto-network
    depends_on:
      - eureka-server
      - lotto-category
      - lotto-transaction

networks:
  lotto-network:
    driver: bridge